#!/usr/bin/env python3
"""
Script to consolidate blog post categories into 10 main categories.
"""

import os
import re
import glob
from pathlib import Path

# Define the category mapping
CATEGORY_MAPPING = {
    # AI & Machine Learning
    'AI Development': 'AI & Machine Learning',
    'AI/ML': 'AI & Machine Learning',
    'AI Systems': 'AI & Machine Learning',
    'Machine Learning': 'AI & Machine Learning',
    'AI Frameworks': 'AI & Machine Learning',
    'Local AI': 'AI & Machine Learning',
    'AI Music Generation': 'AI & Machine Learning',
    'Natural Language Processing': 'AI & Machine Learning',
    'AI Ethics': 'AI & Machine Learning',
    'React Development': 'AI & Machine Learning',
    'Toxicity Detection': 'AI & Machine Learning',
    'Data Science': 'AI & Machine Learning',
    'Rust Development': 'AI & Machine Learning',
    'AI Integration & Development': 'AI & Machine Learning',
    'AI Assistants': 'AI & Machine Learning',
    'NLP Projects': 'AI & Machine Learning',
    'Chatbot Development': 'AI & Machine Learning',
    'Conversational AI': 'AI & Machine Learning',
    'Cultural AI Studies': 'AI & Machine Learning',
    'LLM Research': 'AI & Machine Learning',
    'Technology': 'AI & Machine Learning',
    'LLM Architecture': 'AI & Machine Learning',
    'Industry Insights': 'AI & Machine Learning',
    'AI Tools': 'AI & Machine Learning',
    'Software Development': 'AI & Machine Learning',
    'AI Events': 'AI & Machine Learning',
    'Open Source Development': 'AI & Machine Learning',
    'Community Projects': 'AI & Machine Learning',
    'Programming': 'AI & Machine Learning',
    'Artificial Intelligence': 'AI & Machine Learning',
    'Information Processing': 'AI & Machine Learning',
    'AI Tutoring': 'AI & Machine Learning',
    'VSCode Extensions': 'AI & Machine Learning',
    'LLM Integration': 'AI & Machine Learning',
    'Local LLMs': 'AI & Machine Learning',
    'AI Research': 'AI & Machine Learning',
    'Deep Learning': 'AI & Machine Learning',
    'AI Algorithms': 'AI & Machine Learning',
    'Decision Making': 'AI & Machine Learning',
    'Neural Networks': 'AI & Machine Learning',
    'AI Safety': 'AI & Machine Learning',
    'Model-Based RL': 'AI & Machine Learning',
    'Offline RL': 'AI & Machine Learning',
    'Hierarchical RL': 'AI & Machine Learning',
    'Large Language Models': 'AI & Machine Learning',
    'Technical Education': 'AI & Machine Learning',
    'AI Content': 'AI & Machine Learning',
    'Content Analysis': 'AI & Machine Learning',
    'Technical Guides': 'AI & Machine Learning',
    'AI Theory': 'AI & Machine Learning',
    'AI Applications': 'AI & Machine Learning',
    'Content Tools': 'AI & Machine Learning',
    'Tutorial Guides': 'AI & Machine Learning',
    'Open Source': 'AI & Machine Learning',
    'Agent Architecture': 'AI & Machine Learning',
    'Philosophy': 'AI & Machine Learning',
    'AI Censorship': 'AI & Machine Learning',
    'Synthetic Media': 'AI & Machine Learning',
    'Digital Ethics': 'AI & Machine Learning',
    'AI Platform': 'AI & Machine Learning',
    'ML Ops': 'AI & Machine Learning',
    'AI Business': 'AI & Machine Learning',
    'Entrepreneurship': 'AI & Machine Learning',
    'AI Innovation': 'AI & Machine Learning',
    'Local AI Setup': 'AI & Machine Learning',
    'Model Integration': 'AI & Machine Learning',
    'Code Completion': 'AI & Machine Learning',
    'AI Deployment': 'AI & Machine Learning',
    'Cross-Language Integration': 'AI & Machine Learning',
    'Model Training': 'AI & Machine Learning',
    'Performance Optimization': 'AI & Machine Learning',
    'AI Model Training': 'AI & Machine Learning',
    'Local Deployment': 'AI & Machine Learning',
    'Rust AI': 'AI & Machine Learning',
    'Python Integration': 'AI & Machine Learning',
    'AI Infrastructure': 'AI & Machine Learning',
    'Enterprise AI': 'AI & Machine Learning',
    'Distributed AI': 'AI & Machine Learning',
    'Cognitive Architecture': 'AI & Machine Learning',
    'AI Philosophy': 'AI & Machine Learning',
    'AI Theory': 'AI & Machine Learning',
    'Distributed Systems': 'AI & Machine Learning',
    'Microservices': 'AI & Machine Learning',
    'AI Collaboration': 'AI & Machine Learning',
    'Writing Style Imitation': 'AI & Machine Learning',
    'Vector Databases': 'AI & Machine Learning',
    'Embeddings': 'AI & Machine Learning',
    'Document Processing': 'AI & Machine Learning',
    'Text Extraction': 'AI & Machine Learning',
    'Semantic Analysis': 'AI & Machine Learning',
    'Sentence Transformers': 'AI & Machine Learning',
    'Vector Embeddings': 'AI & Machine Learning',
    'Information Retrieval': 'AI & Machine Learning',
    'Vector Search': 'AI & Machine Learning',
    'Document Analysis': 'AI & Machine Learning',
    'Text Processing': 'AI & Machine Learning',
    'Ollama': 'AI & Machine Learning',
    'Text Chunking': 'AI & Machine Learning',
    'Semantic Chunking': 'AI & Machine Learning',
    'Hierarchical Chunking': 'AI & Machine Learning',
    'Sliding Window': 'AI & Machine Learning',
    'Natural Language Processing': 'AI & Machine Learning',
    'AI Development': 'AI & Machine Learning',
    'AI': 'AI & Machine Learning',
    'LLM': 'AI & Machine Learning',
    'AI/ML': 'AI & Machine Learning',
    'Machine Learning': 'AI & Machine Learning',
    'AI Frameworks': 'AI & Machine Learning',
    'Local AI': 'AI & Machine Learning',
    'AI Ethics': 'AI & Machine Learning',
    'Data Science': 'AI & Machine Learning',
    'AI Tools': 'AI & Machine Learning',
    'Artificial Intelligence': 'AI & Machine Learning',
    'AI Tutoring': 'AI & Machine Learning',
    'LLM Integration': 'AI & Machine Learning',
    'Local LLMs': 'AI & Machine Learning',
    'AI Research': 'AI & Machine Learning',
    'Deep Learning': 'AI & Machine Learning',
    'Neural Networks': 'AI & Machine Learning',
    'Large Language Models': 'AI & Machine Learning',
    'AI Content': 'AI & Machine Learning',
    'Technical Guides': 'AI & Machine Learning',
    'AI Theory': 'AI & Machine Learning',
    'AI Applications': 'AI & Machine Learning',
    'Open Source': 'AI & Machine Learning',
    'Philosophy': 'AI & Machine Learning',
    'AI Censorship': 'AI & Machine Learning',
    'Digital Ethics': 'AI & Machine Learning',
    'AI Platform': 'AI & Machine Learning',
    'AI Business': 'AI & Machine Learning',
    'AI Innovation': 'AI & Machine Learning',
    'AI Infrastructure': 'AI & Machine Learning',
    'Enterprise AI': 'AI & Machine Learning',
    'Distributed AI': 'AI & Machine Learning',
    'AI Philosophy': 'AI & Machine Learning',
    'Distributed Systems': 'AI & Machine Learning',
    'Writing Style Imitation': 'AI & Machine Learning',
    'Vector Databases': 'AI & Machine Learning',
    'Document Processing': 'AI & Machine Learning',
    'Text Processing': 'AI & Machine Learning',
    'Ollama': 'AI & Machine Learning',
    'AI Development': 'AI & Machine Learning',

    # Web Development
    'Web Development': 'Web Development',
    'Full-Stack Development': 'Web Development',
    'Next.js': 'Web Development',
    'React': 'Web Development',
    'Django': 'Web Development',
    'Backend Development': 'Web Development',
    'API Development': 'Web Development',
    'Full-Stack': 'Web Development',
    'Django Development': 'Web Development',
    'Database Design': 'Web Development',
    'Database Refactoring': 'Web Development',
    'Django Models': 'Web Development',
    'API Design': 'Web Development',
    'Backend Development': 'Web Development',
    'API Integration': 'Web Development',
    'Server-Side Rendering': 'Web Development',
    'Firebase': 'Web Development',
    'Authentication': 'Web Development',
    'Firestore': 'Web Development',
    'Real-Time': 'Web Development',
    'Iframe Security': 'Web Development',
    'Admin Dashboard': 'Web Development',
    'Educational Technology': 'Web Development',
    'Web Applications': 'Web Development',
    'Interactive Stories': 'Web Development',
    'Browser Extensions': 'Web Development',
    'Chrome Extension': 'Web Development',
    'Webpack': 'Web Development',
    'Manifest V3': 'Web Development',
    'Downloads API': 'Web Development',
    'JavaScript': 'Web Development',
    'Browser Development': 'Web Development',
    'WebSocket': 'Web Development',
    'Netlify': 'Web Development',
    'Story Creation': 'Web Development',
    'Browser Extensions': 'Web Development',
    'Web Applications': 'Web Development',
    'Interactive Stories': 'Web Development',
    'Browser Extensions': 'Web Development',
    'WebSocket': 'Web Development',
    'Netlify': 'Web Development',

    # Tutorial & Education
    'Tutorial': 'Tutorial & Education',
    'Tutorial Guides': 'Tutorial & Education',
    'Technical Tutorials': 'Tutorial & Education',
    'Education Technology': 'Tutorial & Education',
    'AI Tutoring': 'Tutorial & Education',
    'Learning Platform': 'Tutorial & Education',
    'Interactive Quizzes': 'Tutorial & Education',
    'Personalized Learning': 'Tutorial & Education',
    'Adaptive Learning': 'Tutorial & Education',
    'Educational Technology': 'Tutorial & Education',
    'Quiz Platform': 'Tutorial & Education',
    'Teaching Assistant': 'Tutorial & Education',
    'Markdown Processing': 'Tutorial & Education',
    'Knowledge Graphs': 'Tutorial & Education',
    'FastAPI': 'Tutorial & Education',
    'PostgreSQL': 'Tutorial & Education',
    'ChromaDB': 'Tutorial & Education',
    'RAG': 'Tutorial & Education',
    'Next.js': 'Tutorial & Education',
    'Tutorial': 'Tutorial & Education',
    'Guide': 'Tutorial & Education',
    'Tutorial': 'Tutorial & Education',

    # Business & Entrepreneurship
    'Business Strategy': 'Business & Entrepreneurship',
    'Company Building': 'Business & Entrepreneurship',
    'Tech Startups': 'Business & Entrepreneurship',
    'Business Planning': 'Business & Entrepreneurship',
    'Business': 'Business & Entrepreneurship',
    'Case Study': 'Business & Entrepreneurship',
    'Career Development': 'Business & Entrepreneurship',
    'Professional Development': 'Business & Entrepreneurship',
    'Freelancing': 'Business & Entrepreneurship',
    'Developer Career': 'Business & Entrepreneurship',
    'Entrepreneurship': 'Business & Entrepreneurship',
    'Art & Design': 'Business & Entrepreneurship',
    'Business': 'Business & Entrepreneurship',
    'Automation': 'Business & Entrepreneurship',
    'Case Study': 'Business & Entrepreneurship',
    'Micro-Enterprise': 'Business & Entrepreneurship',
    'Art Business': 'Business & Entrepreneurship',
    'Sticker Art': 'Business & Entrepreneurship',
    'Business Automation': 'Business & Entrepreneurship',
    'Organic Marketing': 'Business & Entrepreneurship',
    'E-commerce': 'Business & Entrepreneurship',
    'Independent Art': 'Business & Entrepreneurship',
    'Sustainable Business': 'Business & Entrepreneurship',
    'Local Business': 'Business & Entrepreneurship',
    'Creative Entrepreneurship': 'Business & Entrepreneurship',
    'Business Psychology': 'Business & Entrepreneurship',
    'Solo Developer': 'Business & Entrepreneurship',
    'Career Development': 'Business & Entrepreneurship',
    'Upwork': 'Business & Entrepreneurship',
    'Business Strategy': 'Business & Entrepreneurship',
    'Company Building': 'Business & Entrepreneurship',
    'Startup': 'Business & Entrepreneurship',
    'Business Planning': 'Business & Entrepreneurship',
    'ML Startup': 'Business & Entrepreneurship',
    'Startup Plan': 'Business & Entrepreneurship',
    'Entrepreneurship': 'Business & Entrepreneurship',
    'Scaling': 'Business & Entrepreneurship',
    'Business Plan': 'Business & Entrepreneurship',
    'Tech Company': 'Business & Entrepreneurship',
    'Data Annotation': 'Business & Entrepreneurship',
    'Scaling': 'Business & Entrepreneurship',
    'Entrepreneurship': 'Business & Entrepreneurship',

    # Agent Development
    'AI Agents': 'Agent Development',
    'Agent Development': 'Agent Development',
    'Chatbots': 'Agent Development',
    'Customer Service': 'Agent Development',
    'Multi-Agent Systems': 'Agent Development',
    'Agent Frameworks': 'Agent Development',
    'Custom Agents': 'Agent Development',
    'AI Customer Support': 'Agent Development',
    'Social Media Automation': 'Agent Development',
    'Content Marketing': 'Agent Development',
    'Automation': 'Agent Development',
    'OpenAI Agents SDK': 'Agent Development',
    'Agent Development': 'Agent Development',
    'Local AI Agents': 'Agent Development',
    'Custom Agent Framework': 'Agent Development',
    'AI Task Automation': 'Agent Development',
    'Real-Time Streaming': 'Agent Development',
    'Task Decomposition': 'Agent Development',
    'Agent Workflows': 'Agent Development',
    'Production Deployment': 'Agent Development',
    'Multi-Agent Systems': 'Agent Development',
    'AutoGen': 'Agent Development',
    'AI Collaboration': 'Agent Development',
    'SDLC Automation': 'Agent Development',
    'Tech Workflow': 'Agent Development',
    'NetworkX': 'Agent Development',
    'AI Workflow': 'Agent Development',
    'Content Generation': 'Agent Development',
    'Social Media': 'Agent Development',
    'Python Automation': 'Agent Development',
    'API Integration': 'Agent Development',
    'Multi-Platform': 'Agent Development',
    'Content Distribution': 'Agent Development',
    'AI Automation': 'Agent Development',
    'Browser-Use': 'Agent Development',
    'AI Knowledge Companion': 'Agent Development',
    'Web Automation': 'Agent Development',
    'Intelligent Research': 'Agent Development',
    'Semantic Search': 'Agent Development',
    'AI Agents': 'Agent Development',
    'Agent Development': 'Agent Development',
    'Chatbots': 'Agent Development',
    'Multi-Agent Systems': 'Agent Development',
    'Agent Frameworks': 'Agent Development',
    'OpenAI Agents SDK': 'Agent Development',
    'Custom Agents': 'Agent Development',
    'AI Task Automation': 'Agent Development',
    'Agent Workflows': 'Agent Development',
    'Multi-Agent Systems': 'Agent Development',
    'AI Collaboration': 'Agent Development',
    'Content Generation': 'Agent Development',
    'Python Automation': 'Agent Development',
    'AI Automation': 'Agent Development',
    'AI Agents': 'Agent Development',

    # Tools & Integration
    'Tools & Integration': 'Tools & Integration',
    'API Integration': 'Tools & Integration',
    'LangChain': 'Tools & Integration',
    'RAG Implementation': 'Tools & Integration',
    'Vector Databases': 'Tools & Integration',
    'OpenAI': 'Tools & Integration',
    'Pydantic': 'Tools & Integration',
    'RAG': 'Tools & Integration',
    'LLM Agents': 'Tools & Integration',
    'Persona Generation': 'Tools & Integration',
    'AI Tooling': 'Tools & Integration',
    'OpenAI API': 'Tools & Integration',
    'Content Generation': 'Tools & Integration',
    'AI Agents': 'Tools & Integration',
    'Writer Styling': 'Tools & Integration',
    'Pydantic AI': 'Tools & Integration',
    'Agent Development': 'Tools & Integration',
    'Custom AI': 'Tools & Integration',
    'Ollama': 'Tools & Integration',
    'LangChain': 'Tools & Integration',
    'OpenAI': 'Tools & Integration',
    'ChromaDB': 'Tools & Integration',
    'Vector Search': 'Tools & Integration',
    'Document Processing': 'Tools & Integration',
    'Embeddings': 'Tools & Integration',
    'NLP': 'Tools & Integration',
    'Tutorial': 'Tools & Integration',
    'Chatbot Development': 'Tools & Integration',
    'Conversational AI': 'Tools & Integration',
    'AI Assistants': 'Tools & Integration',
    'Vector Databases': 'Tools & Integration',
    'Retrieval-Augmented Generation': 'Tools & Integration',
    'Pydantic AI': 'Tools & Integration',
    'Agent Development': 'Tools & Integration',
    'Custom AI': 'Tools & Integration',
    'OpenAI API': 'Tools & Integration',
    'Content Generation': 'Tools & Integration',
    'Writer Styling': 'Tools & Integration',
    'Pydantic': 'Tools & Integration',
    'RAG': 'Tools & Integration',
    'LLM Agents': 'Tools & Integration',
    'Persona Generation': 'Tools & Integration',
    'AI Tooling': 'Tools & Integration',
    'Ollama': 'Tools & Integration',
    'ChromaDB': 'Tools & Integration',
    'Document Processing': 'Tools & Integration',
    'NLP': 'Tools & Integration',
    'AI Assistants': 'Tools & Integration',
    'Vector Databases': 'Tools & Integration',
    'Pydantic AI': 'Tools & Integration',
    'Custom AI': 'Tools & Integration',
    'OpenAI API': 'Tools & Integration',
    'Writer Styling': 'Tools & Integration',

    # Ethics & Philosophy
    'Ethics & Philosophy': 'Ethics & Philosophy',
    'AI Ethics': 'Ethics & Philosophy',
    'Philosophy': 'Ethics & Philosophy',
    'Cultural AI Studies': 'Ethics & Philosophy',
    'LLM Research': 'Ethics & Philosophy',
    'AI Ethics': 'Ethics & Philosophy',
    'Cultural Bias': 'Ethics & Philosophy',
    'LLMs': 'Ethics & Philosophy',
    'LLaMA': 'Ethics & Philosophy',
    'QwQ': 'Ethics & Philosophy',
    'Mistral': 'Ethics & Philosophy',
    'Guardrails': 'Ethics & Philosophy',
    'Cross-cultural Analysis': 'Ethics & Philosophy',
    'AI Ethics': 'Ethics & Philosophy',
    'Cultural Bias': 'Ethics & Philosophy',
    'LLMs': 'Ethics & Philosophy',
    'Cross-cultural Analysis': 'Ethics & Philosophy',

    # Content & Media
    'Content & Media': 'Content & Media',
    'Writing & Content Generation': 'Content & Media',
    'Content Creation': 'Content & Media',
    'Social Media Analytics': 'Content & Media',
    'Content Generation': 'Content & Media',
    'Social Media': 'Content & Media',
    'Writing': 'Content & Media',
    'Content Marketing': 'Content & Media',
    'Social Media Automation': 'Content & Media',
    'Content Generation': 'Content & Media',
    'Social Media': 'Content & Media',
    'Python': 'Content & Media',
    'API Integration': 'Content & Media',
    'Social Media Marketing': 'Content & Media',
    'Multi-Platform': 'Content & Media',
    'Content Distribution': 'Content & Media',
    'AI Automation': 'Content & Media',
    'Instagram API': 'Content & Media',
    'Image Captioning': 'Content & Media',
    'Persona Analysis': 'Content & Media',
    'LLMs': 'Content & Media',
    'Python': 'Content & Media',
    'Reddit API': 'Content & Media',
    'PRAW': 'Content & Media',
    'OpenAI': 'Content & Media',
    'Persona Generation': 'Content & Media',
    'Python Automation': 'Content & Media',
    'Content Generation': 'Content & Media',
    'Social Media': 'Content & Media',
    'Python': 'Content & Media',
    'API Integration': 'Content & Media',
    'Social Media Marketing': 'Content & Media',
    'Multi-Platform': 'Content & Media',
    'Content Distribution': 'Content & Media',
    'AI Automation': 'Content & Media',

    # System Architecture
    'System Architecture': 'System Architecture',
    'Backend Development': 'System Architecture',
    'Distributed Systems': 'System Architecture',
    'Enterprise Software': 'System Architecture',
    'Scalable Architecture': 'System Architecture',
    'Async Programming': 'System Architecture',
    'Task Queues': 'System Architecture',
    'Caching': 'System Architecture',
    'Database Optimization': 'System Architecture',
    'Kubernetes': 'System Architecture',
    'Vector Databases': 'System Architecture',
    'Scalable Architecture': 'System Architecture',
    'Distributed Computing': 'System Architecture',
    'System Design': 'System Architecture',
    'Enterprise AI': 'System Architecture',
    'Microservices': 'System Architecture',
    'FastAPI': 'System Architecture',
    'PostgreSQL': 'System Architecture',
    'Redis': 'System Architecture',
    'Celery': 'System Architecture',
    'RabbitMQ': 'System Architecture',
    'Scalable Architecture': 'System Architecture',
    'Async Programming': 'System Architecture',
    'Task Queues': 'System Architecture',
    'Caching': 'System Architecture',
    'Database Optimization': 'System Architecture',
    'Kubernetes': 'System Architecture',
    'Vector Databases': 'System Architecture',
    'Distributed Computing': 'System Architecture',
    'System Design': 'System Architecture',
    'Microservices': 'System Architecture',

    # Personal Development
    'Personal Development': 'Personal Development',
    'Personal Knowledge Management': 'Personal Development',
    'Self-Hosted Applications': 'Personal Development',
    'Jekyll': 'Personal Development',
    'Personal Development': 'Personal Development',
    'Local AI': 'Personal Development',
    'Knowledge Management': 'Personal Development',
    'Productivity': 'Personal Development',
    'Personal Resilience': 'Personal Development',
    'Community Resources': 'Personal Development',
    'Austin Homeless Services': 'Personal Development',
    'Personal Recovery': 'Personal Development',
    'Shelter Resources': 'Personal Development',
    'Employment': 'Personal Development',
    'Mental Health': 'Personal Development',
    'Legal Rights': 'Personal Development',
    'Poverty Alleviation': 'Personal Development',
    'Community Support': 'Personal Development',
    'Homelessness': 'Personal Development',
    'Austin': 'Personal Development',
    'Personal Recovery': 'Personal Development',
    'insight': 'Personal Development',
    'Journaling': 'Personal Development',
    'Privacy': 'Personal Development',
    'Self-Hosting': 'Personal Development',
    'Personal Development': 'Personal Development',
    'Local AI': 'Personal Development',
    'Knowledge Management': 'Personal Development',
    'Personal Knowledge Management': 'Personal Development',
    'Self-Hosted Applications': 'Personal Development',
    'Jekyll': 'Personal Development',
    'Personal Development': 'Personal Development',
    'Local AI': 'Personal Development',
    'Knowledge Management': 'Personal Development',
}

def consolidate_categories(categories):
    """Consolidate a list of categories into the 10 main categories."""
    consolidated = set()

    for category in categories:
        # Remove quotes and whitespace
        category = category.strip(' "\'')

        # Map to new category if it exists in mapping
        if category in CATEGORY_MAPPING:
            consolidated.add(f'"{CATEGORY_MAPPING[category]}"')
        else:
            # Keep original if no mapping found
            consolidated.add(f'"{category}"')

    return sorted(list(consolidated))

def process_blog_posts():
    """Process all blog posts and update their categories."""
    blog_dir = 'content/blog'
    processed_count = 0

    # Find all markdown files in the blog directory
    for md_file in Path(blog_dir).glob('*.md'):
        try:
            with open(md_file, 'r', encoding='utf-8') as f:
                content = f.read()

            # Find categories line
            categories_match = re.search(r'categories:\s*\[(.*?)\]', content, re.DOTALL)

            if categories_match:
                categories_str = categories_match.group(1)
                # Extract individual categories
                categories = [cat.strip() for cat in categories_str.split(',')]

                # Consolidate categories
                new_categories = consolidate_categories(categories)

                # Replace in content
                old_categories_line = f'categories: [{categories_str}]'
                new_categories_line = f'categories: [{", ".join(new_categories)}]'

                if old_categories_line != new_categories_line:
                    content = content.replace(old_categories_line, new_categories_line)

                    # Write back to file
                    with open(md_file, 'w', encoding='utf-8') as f:
                        f.write(content)

                    processed_count += 1
                    print(f"Updated {md_file.name}: {categories} -> {new_categories}")

        except Exception as e:
            print(f"Error processing {md_file}: {e}")

    return processed_count

if __name__ == "__main__":
    print("Starting category consolidation...")
    processed = process_blog_posts()
    print(f"Processed {processed} blog posts.")
